[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
repository = "https://github.com/zjom/snot"
license = "MIT"

[workspace.dependencies]
snot-syntax = { path = "crates/snot-syntax", version = "0.1.0" }
snot-fmt = { path = "crates/snot-fmt", version = "0.1.0" }
snot-workspace = { path = "crates/snot-workspace", version = "0.1.0" }
snot-check = { path = "crates/snot-check", version = "0.1.0" }
snot-lsp = { path = "crates/snot-lsp", version = "0.1.0" }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
