[package]
name = "snot-fmt"
description = "Formatter for Simple Note Format."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
snot-syntax.workspace = true
unicode-width = "0.2"

[lints]
workspace = true

[dev-dependencies]
proptest = "1"
