[package]
name = "snot-lsp"
description = "Language server for Simple Note Format."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
snot-syntax.workspace = true
snot-fmt.workspace = true
snot-workspace.workspace = true
snot-check.workspace = true
lsp-server = "0.10"
lsp-types = "0.95"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
crossbeam-channel = "0.5"

[lints]
workspace = true

[dev-dependencies]
lsp-server = "0.10"
lsp-types = "0.95"
tempfile = "3"
